baseURL = "https://luciamontesinos.github.io/london-mobility/"
languageCode = "en-us"
title = "London Mobility"
publishDir = "docs"
theme = "PaperMod"
[Params] 
    author = ["Lucía Montesinos García - s205912", "Max Jacob Specktor - s184362", "Tamás Rudokász - s202522"]
    description = "Final project for 02806 Social data analysis and visualization Spring 21"
    [params.homeInfoParams]
        title = "Hi there wave"
        content = "Can be Info, links, about..."

    [params.socialIcons]
        name = "github"
            url = "github"


[[fruit]]
name = "apple"

[fruit.physical]
color = "red"
shape = "round"            

[[menu.main]]
    url = "/home"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/london"
    name = "London"
    weight = 2

[[menu.main]]
    url = "/covid"
    name = "Covid-19"
    weight = 3
[[menu.main]]
    url = "/mobility"
    name = "Mobility"
    weight = 3

