baseURL = "https://luciamontesinos.github.io/london-mobility/"
languageCode = "en-us"
title = "London Mobility"
publishDir = "docs"
theme = "PaperMod"
[Params] 
author = ["Lucía Montesinos García - s205912", "Max Jacob Specktor - s184362", "Tamás Rudokász - s202522"]
description = "Final project for 02806 Social data analysis and visualization Spring 21"

ShowShareButtons = true
[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, links, about..."

[[params.socialIcons]]
name = "github"
url = "https://github.com/luciamontesinos/london-mobility"
[assets]
    favicon= "/favicon.ico"

[[menu.main]]
    url = "/london"
    name = "London"
    weight = 2

[[menu.main]]
    url = "/covid"
    name = "Covid-19"
    weight = 3
[[menu.main]]
    url = "/mobility"
    name = "Mobility"
    weight = 3

